import { SubtypeClass } from './types.js';

type PatternConfig = { class: SubtypeClass; patterns: string[] };

export const SUBTYPE_CLASS_PATTERNS: PatternConfig[] = [
  {
    class: 'accessory',
    patterns: [
      'accessory',
      'case',
      'cover',
      'charger',
      'cable',
      'adapter',
      'battery',
      'lens',
      'strap',
      'stand',
      'dock',
      'mount',
      'holder',
      'protector',
      'replacement',
    ],
  },
  {
    class: 'device',
    patterns: [
      'phone',
      'smartphone',
      'laptop',
      'tablet',
      'camera',
      'console',
      'smartwatch',
      'watch',
      'headphone',
      'earbud',
      'speaker',
      'router',
      'printer',
      'monitor',
      'tv',
    ],
  },
  {
    class: 'apparel',
    patterns: [
      'apparel',
      'clothing',
      'textile',
      'shoe',
      'sneaker',
      'boot',
      'bag',
      'handbag',
      'backpack',
      'dress',
      'jacket',
      'coat',
      'pants',
      'jean',
      'shirt',
      'tshirt',
      'skirt',
      'hat',
    ],
  },
  {
    class: 'furniture',
    patterns: [
      'furniture',
      'chair',
      'table',
      'sofa',
      'couch',
      'bed',
      'desk',
      'dresser',
      'cabinet',
      'shelf',
      'wardrobe',
    ],
  },
  {
    class: 'media',
    patterns: ['book', 'dvd', 'cd', 'vinyl', 'blu-ray', 'game'],
  },
];
