package com.scanium.shared.core.models.listing

import com.scanium.shared.core.models.assistant.ConfidenceTier
import kotlinx.serialization.Serializable

/**
 * Result of AI-generated marketplace listing content.
 *
 * Generated by the Assistant API based on item attributes and images.
 *
 * @property title Generated listing title (e.g., "Dell XPS 15 Laptop - Silver, Excellent Condition")
 * @property description Generated listing description
 * @property titleConfidence Confidence tier for the generated title
 * @property descriptionConfidence Confidence tier for the generated description
 * @property warnings List of warnings/suggestions for user verification
 * @property suggestedNextPhoto Suggestion for additional photo if evidence is insufficient
 */
@Serializable
data class GeneratedListing(
    val title: String,
    val description: String,
    val titleConfidence: ConfidenceTier = ConfidenceTier.MED,
    val descriptionConfidence: ConfidenceTier = ConfidenceTier.MED,
    val warnings: List<GeneratedListingWarning> = emptyList(),
    val suggestedNextPhoto: String? = null,
)

/**
 * Warning or verification suggestion for a generated listing.
 *
 * @property field The field this warning relates to (e.g., "title", "description", "model")
 * @property message Human-readable warning message
 * @property type Type of warning (needs verification, low confidence, etc.)
 */
@Serializable
data class GeneratedListingWarning(
    val field: String,
    val message: String,
    val type: WarningType = WarningType.NEEDS_VERIFICATION,
)

/**
 * Type of listing generation warning.
 */
@Serializable
enum class WarningType {
    /** Attribute or field needs manual verification */
    NEEDS_VERIFICATION,
    /** Low confidence in the generated content */
    LOW_CONFIDENCE,
    /** Missing information that could improve the listing */
    MISSING_INFO,
}
